### ISSUE TITLE
无法运行实验报告中的示例

### ISSUE THREAD

**Issue by kardusenor** [Linyxus/mips-hike#1]
![image](https://user-images.githubusercontent.com/71575606/171142559-bd452a1c-262f-4e09-bce4-6fcda469accb.png)
运行nix-shell shell.nix --run "cabal configure; cabal build"和make build后，再运行如图所示命令后结果如上，加入-e提示后运行结果如下
![image](https://user-images.githubusercontent.com/71575606/171142812-e477ad3c-1066-4ed8-9d2f-7cdb6ddca211.png)

**Comment by Linyxus** [comment]
实验报告中的示例有些老旧了。尝试：`./result/bin/model -s examples/fibo.mem -e examples/inte.mem`。

**Comment by kardusenor** [comment]
thx!
